#[functions."readUsers2"]
#  included_files = ["@supabase/supabase-js"]
# # node_bundler = "esbuild"
 # external_node_modules = [
 #   "@supabase/supabase-js",
  #  "@supabase/gotrue-js"
  #   ]
 [functions]
   directory = "functions"
   [functions."readUsers2"]
    external_node_modules = ["@supabaseyyyy/supabase-js"]
